version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app/temp:/app/app/temp

  frontend:
    build: ./meeting-summarizer
    ports:
      - "5173:5173" 