name: Run tests and upload coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # FRONTEND
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install frontend dependencies
        run: npm install
        working-directory: meeting-summarizer

      - name: Install frontend test dependencies
        run: npm install --save-dev @vue/test-utils@next @vue/vue3-jest@^27.0.0 jest@^27.5.1 babel-jest@^27.5.1
        working-directory: meeting-summarizer

      - name: Run frontend tests
        run: npx jest --coverage
        working-directory: meeting-summarizer

      # BACKEND
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install pytest and pytest-cov
        run: pip install pytest pytest-cov

      - name: Run backend tests
        run: PYTHONPATH=. pytest --cov=app --cov-report=xml:coverage.xml
        working-directory: backend

      # UPLOAD COVERAGE (gabung)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: dev-shiki/aisum
          files: meeting-summarizer/coverage/lcov.info,backend/coverage.xml 